'''
Created on Nov 8, 2018

@author: paepcke
'''
acad_grp_name_root = {
     'AA'     : 'ENGR',
     'ACCT'  : 'GSB',
     'AFRICA' : 'H&S',
     'AME'   : 'H&S',        
     'AMSTUD' : 'H&S',
     'ANES' : 'MED',
     'ANTHRO' : 'H&S',
     'ANTHSCI' : 'H&S',
     'APP' : 'H&S',        
     'ARCH'   : 'H&S',
     'ART' : 'H&S',
     'ARAB' : 'H&S',
     'ASN' : 'H&S',        
     'ATHLETIC' : 'ATH',  # officially: Health and Human Performance
     'BIOC' : 'MED',
     'BIODS' : 'MED',
     'BIOE' : 'ENGR',
     'BIOH' : 'H&S',
     'BIOM' : 'MED',
     'BIOPH' : 'H&S',
     'BIO' : 'H&S',
     'BIOS' : 'MED',
     'BUSINESS' : 'GSB',
     'CAT' : 'H&S',
     'CBIO' : 'MED',
     'CE-MS' : 'ENGR',
     'CEE' : 'ENGR',
     'CHEM' : 'H&S',
     'CHEMENG' : 'ENGR',
     'CHIL' : 'H&S',
     'CHIN' : 'H&S',        
     'CHICAN' : 'H&S',
     'CHPR' : 'MED',
     'CLASS' : 'H&S',
     'CME' : 'ENGR',
     'COMM' : 'H&S',
     'COMPLIT' : 'H&S',
     'COMPMED' : 'MED',        
     'CS' : 'ENGR',
     'CSRE' : 'H&S',
     'CTL' : 'H&S',
     'CTS' : 'MED',        
     'DAN' : 'H&S',
     'DBIO' : 'H&S',        
     'DDRL' : 'H&S',
     'DERM' : 'MED',
     'DESINST' : 'ENGR',        
     'DLCL' : 'H&S',  
     'DRAMA' : 'H&S',
     'EALC' : 'H&S',        
     'EARTH' : 'EARTH',
     'EAST' : 'H&S',
     'ECON' : 'H&S',        
     'EDUC' : 'EDUC',
     'EESOR' : 'ENGR',
     'EEES'  : 'EARTH',
     'EESS'  : 'EARTH',
     'EES'   : 'ENGR',
     'EE'    : 'ENGR',
     'EFS'   : 'H&S',
     'EMED'    : 'MED',        
     'ENERGY' : 'EARTH',
     'ENGL-BA' : 'H&S',
     'ENGLISH' : 'H&S',
     'ENGR' : 'ENGR',
     'ENGR-MS' : 'ENGR',
     'ETHI' : 'H&S',
     'ENV' : 'EARTH',
     'ESF' : 'VPUE',        
     'ESS' : 'EARTH',
     'FAMMED' : 'MED',
     'FEM' : 'H&S',
     'FILM' : 'H&S',        
     'FINAN' : 'GSB',
     'FREN' : 'H&S',
     'GS' : 'EARTH',
     'GENE' : 'MED',
     'GEOP' : 'EARTH',        
     'GER' : 'H&S',
     'GES' : 'H&S',
     'GLOBAL' : 'H&S',
     'GSBGEN' : 'EDUC',
     'GYOB' : 'MED',
     'HISTORY' : 'H&S',
     'HRM' : 'GSB',
     'HRP' : 'MED',        
     'HPS' : 'H&S',
     'HRP' : 'H&S',        
     'HUM' : 'H&S',
     'IBER' : 'H&S',
     'ICA' : 'H&S',
     'IE' : 'ENGR',
     'IE-MS' : 'ENGR',
     'IIS' : 'H&S',        
     'IHUM' : 'H&S',        
     'ILAC' : 'H&S',
     'IMMUNOL' : 'MED',
     'INDE' : 'MED',
     'INTN' : 'H&S',        
     'IPS' : 'H&S',        
     'ITAL' : 'H&S',
     'JAP' : 'H&S',
     'JEWISH' : 'H&S',
     'KIN' : 'MED',
     'KOR' : 'H&S',
     'LATI' : 'H&S',
     'LAW' : 'LAW',
     'LEAD' : 'VPUE',
     'LIFE' : 'MED',
     'LIN' : 'H&S',
     'MKTG' : 'GSB',
     'MATH' : 'H&S',
     'MATSCI' : 'ENGR',        
     'MCP' : 'MED',
     'MCS' : 'H&S',        
     'MED' : 'H&S',
     'MGTECON' : 'GSB',
     'MI' : 'MED',
     'MLA' : 'OTHERS',
     'MPHA': 'MED',
     'MS&E' : 'ENGR',
     'MTL' : 'H&S',
     'MUSIC' : 'H&S',        
     'NATIVE' : 'H&S',
     'NEPR' : 'MED',
     'NBIO' : 'MED',
     'NSUR' : 'MED',
     'NENS' : 'H&S',
     'OPHT' : 'MED',                
     'ORTH' : 'MED',
     'OB'   : 'GSB',        
     'OBG'   : 'MED',
     'OIT' : 'GSB',
     'ORAL' : 'VPUE',        
     'OSP' : 'VPUE',
     'OTO' : 'MED',
     'OUTDOOR' : 'MED',   # Also in H&S
     'PAS' : 'MED',
     'PATH' : 'MED',
     'PEDS' : 'MED',
     'PE'   : 'ATH',  # officially: Health and Human Performance
     'PHIL' : 'H&S',
     'PHOTON' : 'H&S',
     'PHYSICS' : 'H&S',
     'POLE'  : 'GSB',
     'POLISC' : 'H&S',
     'POLSC-BA' : 'H&S',
     'PORT' : 'H&S',        
     'PSY' : 'H&S',
     'PUB' : 'H&S',        
     'PWR' : 'VPUE',
     'RAD' : 'MED',
     'RADO' : 'MED',
     'REES' : 'H&S',        
     'RELIG' : 'H&S',
     'RESPROG' : 'VPUE',
     'ROTC' : 'VPUE',
     'SBIO' : 'MED',
     'SCCM' : "H&S",
     'SIMILE' : "VPUE",        
     'SINY' : 'VPUE',
     'SIS'  : 'VPUE',
     'SIW' : 'H&S',        
     'SLAVIC' : 'H&S',
     'SLE' : 'VPUE',
     'SOC' : 'H&S',
     'SOMGEN' : 'MED',        
     'SPAN' : 'H&S',        
     'SPECLAN' : 'H&S',
     'SPEC' : 'OTHERS',
     'STATS' : 'H&S',
     'STEMREM' : 'MED',        
     'STRA' : 'GSB',
     'STS' : 'H&S',
     'SUST' : 'EARTH',
     'SYMBSYS' :  'H&S',      
     'SYMSYS' :  'H&S',      
     'SURG' : 'MED',
     'TAPS' : 'H&S',
     'THINK' : 'VPUE',
     'TIBET' : 'H&S',
     'URBANST' : 'H&S',
     'UAR' : 'VPUE',
     'UROL'  : 'MED',
     'VPTL' : 'OTHERS',
     'WELLNESS' : 'H&S',
     }    

majors = ['AA-BS',  
          'AA-ENG',
          'AA-MIN',
          'AA-MS',
          'AA-NM',
          'AA-PD',
          'AA-PHD',
          'AA-PMN',
          'AA-SNF',
          'AA-VSI',
          'AEPHY-MS',
          'AERAS-GRVR',
          'AES-BS',
          'AES-MS',          
          'AES-PD',
          'AES-PHD',          
          'AFRAM-BA',
          'AFRAM-BAH',
          'AFRAM-BAS',
          'AFRAM-BASH',
          'AFRAM-MIN',
          'AFRST-MA',
          'AFRST-MIN',
          'AFRST-NM',
          'AMELLC-MIN',
          'AMSTU-BA',
          'AMSTU-BAH',
          'AMSTU-BAS',
          'AMSTU-MIN',
          'AMSTU-SEC',
          'ANES-GRVR',
          'ANES-MF',
          'ANES-PD',
          'ANES-VSI',
          'ANSCI-BA',
          'ANSCI-BAH',
          'ANSCI-BAS',
          'ANSCI-BASH',
          'ANSCI-MA',
          'ANSCI-MIN',
          'ANSCI-MS',
          'ANSCI-PD',
          'ANSCI-PHD',
          'ANSCI-PMN',
          'ANSCI-SEC',
          'ANTHR-BA',
          'ANTHR-BAH',
          'ANTHR-BAS',
          'ANTHR-BASH',
          'ANTHR-GRVR',
          'ANTHR-MA',
          'ANTHR-MIN',
          'ANTHR-NM',
          'ANTHR-PD',
          'ANTHR-PHD',
          'ANTHR-PMN',
          'ANTHS-BA',          
          'ANTHS-BAH',
          'APLPH-GRVR',
          'APLPH-MS',
          'APLPH-NM',
          'APLPH-PD',
          'APLPH-PHD',
          'APLPH-SNF',
          'APLPH-VSI',
          'APPLNG-PMN',
          'ARCHA-BA',
          'ARCHA-BAH',
          'ARCHA-BAS',
          'ARCHA-BASH',
          'ARCHA-GRVR',
          'ARCHA-MIN',
          'ARCHA-PD',
          'ARCHA-SEC',
          'ART-BA',
          'ART-BAH',
          'ART-BAS',
          'ART-BASH',
          'ART-MA',
          'ART-MFA',
          'ART-MIN',
          'ART-MIN2',
          'ART-MIN3',
          'ART-NM',
          'ART-PHD',
          'ART-PMN',
          'ART-PMN2',
          'ART-SEC',
          'ARTD-MFA',
          'ARTF-MIN',
          'ARTH-PHD',
          'ARTHS-BA',
          'ARTHS-BAH',
          'ARTHS-BAS',
          'ARTHS-GRVR',
          'ARTHS-MA',
          'ARTHS-PHD',
          'ARTHS-PMN',
          'ARTP-BA',
          'ARTP-BAH',
          'ARTP-BAS',
          'ARTP-MFA',
          'ARTP-MIN',
          'ARTS-IHN',
          'ASAM-BA',
          'ASAM-BAH',
          'ASAM-BAS',
          'ASAM-BASH',
          'ASAM-MIN',
          'BBMD-GRVR',
          'BIO-BAS',
          'BIO-BASH',
          'BIO-BS',
          'BIO-BSH',
          'BIO-GRVR',
          'BIO-MIN',
          'BIO-MS',
          'BIO-NM',
          'BIO-PD',
          'BIO-PHD',
          'BIO-SEC',
          'BIO-SNF',
          'BIO-VSI',
          'BIOC-GRVR',
          'BIOC-MS',
          'BIOC-PD',
          'BIOC-PHD',
          'BIOC-VSI',
          'BIODS-GRVR',
          'BIODS-PD',
          'BIOE-BAS',
          'BIOE-BS',
          'BIOE-BSH',
          'BIOE-GRVR',
          'BIOE-MS',
          'BIOE-NM',
          'BIOE-PD',
          'BIOE-PHD',
          'BIOE-PMN',
          'BIOE-SNF',
          'BIOE-VSI',
          'BIOET-PD',
          'BIOL-BAS',
          'BIOL-BASH',
          'BIOL-BS',
          'BIOL-BSH',
          'BIOL-MIN',
          'BIOL-MS',
          'BIOL-NM',
          'BIOL-PD',
          'BIOL-PHD',
          'BIOL-SEC',
          'BIOM-GRVR',
          'BIOM-MS',
          'BIOM-NM',
          'BIOM-PD',
          'BIOM-PHD',
          'BIOM-PMN',
          'BIOM-VSI',
          'BIOMD-GRVR',
          'BIOME-GRVR',
          'BIOME-PD',
          'BIOPH-MS',
          'BIOPH-NM',
          'BIOPH-PD',
          'BIOPH-PHD',
          'BIOSC-GRVR',
          'BMT-VSI',
          'CAM-PHD',
          'CANBI-MS',
          'CANBI-PHD',
          'CANBI-SNF',
          'CANCR-GRVR',
          'CANCR-PD',
          'CASA-BA',
          'CASA-BAH',
          'CASA-BAS',
          'CASA-BASH',
          'CASA-MA',
          'CASA-MIN',
          'CASA-PHD',
          'CASA-PMN',
          'CASA-SEC',
          'CE-BAS',
          'CE-BASH',
          'CE-BS',
          'CE-BSH',
          'CE-ENG',
          'CE-IHN',
          'CE-MIN',
          'CE-MS',
          'CE-PHD',
          'CE-SEC',
          'CEE-BS',
          'CEE-BSH',
          'CEE-ENG',
          'CEE-GRVR',
          'CEE-MS',
          'CEE-NM',
          'CEE-PD',
          'CEE-PHD',
          'CEE-PMN',
          'CHBIO-PHD',
          'CHEM-BAS',
          'CHEM-BASH',
          'CHEM-BS',
          'CHEM-BSH',
          'CHEM-GRVR',
          'CHEM-MIN',
          'CHEM-MS',
          'CHEM-NM',
          'CHEM-PD',
          'CHEM-PHD',
          'CHEM-PMN',
          'CHEM-SNF',
          'CHEM-VSI',
          'CHEME-BAS',
          'CHEME-BS',
          'CHEME-BSH',
          'CHEME-ENG',
          'CHEME-GRVR',
          'CHEME-MIN',
          'CHEME-MS',
          'CHEME-PD',
          'CHEME-PHD',
          'CHEME-SNF',
          'CHEME-VSI',
          'CHICA-BA',
          'CHICA-BAH',
          'CHICA-BAS',
          'CHICA-BASH',
          'CHICA-MIN',
          'CHICA-SEC',
          'CHILT-BA',
          'CHILT-BAH',
          'CHILT-BAS',
          'CHILT-MIN',
          'CHINE-BA',
          'CHINE-BAH',
          'CHINE-BAS',
          'CHINE-IHN',
          'CHINE-MA',
          'CHINE-MIN',
          'CHINE-NM',
          'CHINE-PD',
          'CHINE-PHD',
          'CHINE-PMN',
          'CHPR-MS',
          'CHPR-NM',
          'CLASH-PHD',
          'CLASS-BA',
          'CLASS-BAH',
          'CLASS-BAS',
          'CLASS-BASH',
          'CLASS-GRVR',
          'CLASS-MA',
          'CLASS-MIN',
          'CLASS-NM',
          'CLASS-PD',
          'CLASS-PHD',
          'CLASS-PMN',
          'CME-MS',
          'CME-PD',
          'CME-PHD',
          'CME-PMN',
          'CME-SNF',
          'CMED-NM',
          'CMED-PD',
          'CMED-VSI',
          'COMMU-BA',
          'COMMU-BAH',
          'COMMU-BAS',
          'COMMU-BASH',
          'COMMU-GRVR',
          'COMMU-MA',
          'COMMU-MIN',
          'COMMU-NM',
          'COMMU-PD',
          'COMMU-PHD',
          'COMMU-PMN',
          'COMMU-SEC',
          'COMMUS-BA',
          'CPLIT-BA',
          'CPLIT-BAH',
          'CPLIT-BAS',
          'CPLIT-BASH',
          'CPLIT-GRVR',
          'CPLIT-MA',
          'CPLIT-MIN',
          'CPLIT-NM',
          'CPLIT-PD',
          'CPLIT-PHD',
          'CPLIT-PMN',
          'CPLITH-PHD',
          'CRWRIT-MIN',
          'CS-BAS',
          'CS-BASH',
          'CS-BS',
          'CS-BSH',
          'CS-GRVR',
          'CS-MIN',
          'CS-MS',
          'CS-NM',
          'CS-PD',
          'CS-PHD',
          'CS-PMN',
          'CS-SEC',
          'CS-SNF',
          'CS-VSI',
          'CSB',
          'CSB-GRVR',
          'CSB-MS',
          'CSB-PD',
          'CSB-PHD',
          'CSE-SEC',
          'CSRE-BA',
          'CSRE-BAH',
          'CSRE-BAS',
          'CSRE-BASH',
          'CSRE-IHN',
          'CSRE-MIN',
          'CSRE-SEC',
          'CTS-MF',
          'CTS-PD',
          'CVI-GRVR',
          'CVI-MF',
          'CVI-PD',
          'DATSCI-MIN',
          'DBIO-GRVR',
          'DBIO-MF',
          'DBIO-MS',
          'DBIO-NM',
          'DBIO-PD',
          'DBIO-PHD',
          'DBIO-SNF',
          'DCIF-NM',
          'DCIP-NM',
          'DDRL-IHN',
          'DERM-GRVR',
          'DERM-MF',
          'DERM-PD',
          'DIGHUM-MIN',
          'DRAMA-BA',
          'DRAMA-BAH',
          'DRAMA-BAS',
          'DRAMA-BASH',
          'DRAMA-MA',
          'DRAMA-MIN',
          'DRAMA-NM',          
          'DRAMA-PHD',
          'DRAMAH-PHD',
          'DRAMAH-PMN',
          'DRNMD-MF',
          'DRNMD-PD',
          'EASST-BA',
          'EASST-BAH',
          'EASST-BAS',
          'EASST-BASH',
          'EASST-GRVR',
          'EASST-MA',
          'EASST-MIN',
          'EASST-PD',
          'EASST-SEC',
          'EASYS-BAS',
          'EASYS-BASH',
          'EASYS-BS',
          'EASYS-BSH',
          'EASYS-MA',
          'EASYS-MIN',
          'EASYS-MS',
          'EASYS-SEC',
          'ECON-BA',
          'ECON-BAH',
          'ECON-BAS',
          'ECON-BASH',
          'ECON-GRVR',
          'ECON-MA',
          'ECON-MIN',
          'ECON-NM',
          'ECON-PD',
          'ECON-PHD',
          'ECON-PMN',
          'ECON-RF',
          'ECON-SEC',
          'ECON-VSI',
          'ED-EDD',
          'ED-EDS',
          'ED-IHN',
          'ED-MA',
          'ED-MAT',
          'ED-NM',
          'ED-PD',
          'ED-PHD',
          'ED-PMN',
          'EDUC-GRVR',
          'EDUC-MIN',
          'EDUC-VSI',
          'EDUCH-PHD',
          'EE-BAS',
          'EE-BASH',
          'EE-BS',
          'EE-BSH',
          'EE-ENG',
          'EE-GRVR',
          'EE-MIN',
          'EE-MS',
          'EE-NM',
          'EE-PD',
          'EE-PHD',
          'EE-PMN',
          'EE-SEC',
          'EE-SNF',
          'EE-VSI',
          'EEES-MS',
          'EEES-PHD',
          'EES-PHD',
          'EESOR-ENG',
          'EESOR-MS',
          'EESOR-NM',
          'EESOR-PHD',
          'EESOR-PMN',
          'EESS',
          'EESS-GRVR',
          'EESS-MS',
          'EESS-PD',
          'EESS-PHD',
          'EES-MS',
          'ENGL-BA',
          'ENGL-BAH',
          'ENGL-BAS',
          'ENGL-BASH',
          'ENGL-GRVR',
          'ENGL-MA',
          'ENGL-MIN',
          'ENGL-NM',
          'ENGL-PD',
          'ENGL-PHD',
          'ENGL-SEC',
          'ENGLF-BA',
          'ENGLF-BAH',
          'ENGLF-BAS',
          'ENGLF-BASH',
          'ENGLG-BA',
          'ENGLI-BA',
          'ENGLI-BAH',
          'ENGLS-BA',
          'ENGR-BAS',
          'ENGR-BASH',
          'ENGR-BS',
          'ENGR-BSH',
          'ENGR-GRVR',
          'ENGR-MS',
          'ENGR-NM',
          'ENGR-SEC',
          'ENGROTGRVR',
          'ENVEN-BAS',
          'ENVEN-BS',
          'ENVEN-BSH',
          'ENVEN-MIN',
          'ENVEN-SEC',
          'ENVRES-MS',
          'ENVRES-NM',
          'ENVRES-PHD',
          'ENVSC-GRVR',
          'ENVSE-BS',
          'ENVSE-BSH',
          'ENVSE-MIN',
          'EPIDCR-PHD',
          'EPIDM-MF',
          'EPIDM-MS',
          'EPIDM-NM',
          'EPIDM-PD',
          'EPIDM-PHD',
          'ERE-BAS',
          'ERE-BS',
          'ERE-BSH',
          'ERE-ENG',
          'ERE-GRVR',
          'ERE-MIN',
          'ERE-MS',
          'ERE-NM',
          'ERE-PD',
          'ERE-PHD',
          'ERE-SNF',
          'ERE-VSI',
          'ESS-GRVR',
          'ESS-MS',
          'ESS-PD',
          'ESS-PHD',
          'ESS-VSI',
          'ESTP-IHN',
          'ETHSO-IHN',
          'ETHSO-MIN',
          'FEMST-BA',
          'FEMST-BAH',
          'FEMST-BAS',
          'FEMST-IHN',
          'FEMST-MIN',
          'FEMST-SEC',
          'FGSS-BA',
          'FGSS-BAH',
          'FGSS-BAS',
          'FGSS-IHN',
          'FGSS-MIN',
          'FGSS-PMN',
          'FGSS-SEC',
          'FILM-BA',
          'FILM-BAH',
          'FILM-BAS',
          'FILM-BASH',
          'FILM-MFA',
          'FILM-MIN',
          'FMATH-MS',
          'FMATH-NM',
          'FOODR-MA',
          'FOODR-PHD',
          'FRENC-BA',
          'FRENC-BAH',
          'FRENC-BAS',
          'FRENC-MA',
          'FRENC-MIN',
          'FRENC-NM',
          'FRENC-PD',
          'FRENC-PHD',
          'FRENCH-PHD',
          'FRENE-BAH',
          'FRENI-BA',
          'FRES-MF',
          'FRES-PD',
          'FRNIT-GRVR',
          'FRNIT-PHD',
          'GASTH-GRVR',
          'GDSPC1-PHD',
          'GENE-GRVR',
          'GENE-MF',
          'GENE-MS',
          'GENE-NM',
          'GENE-PD',
          'GENE-PHD',
          'GENE-PMN',
          'GENE-SNF',
          'GENE-VSI',
          'GEOL-BS',
          'GEOL-BSH',          
          'GEOPH-BS',
          'GEOPH-BSH',
          'GEOPH-GRVR',
          'GEOPH-MIN',
          'GEOPH-MS',
          'GEOPH-NM',
          'GEOPH-PD',
          'GEOPH-PHD',
          'GEOPH-VSI',
          'GERST-BA',
          'GERST-BAH',
          'GERST-BAS',
          'GERST-BASH',
          'GERST-GRVR',
          'GERST-MA',
          'GERST-MIN',
          'GERST-PD',
          'GERST-PHD',
          'GERST-SEC',
          'GERSTH-PHD',
          'GES-BAS',
          'GES-BASH',
          'GES-BS',
          'GES-BSH',
          'GES-GRVR',
          'GES-MIN',
          'GES-MS',
          'GES-NM',
          'GES-PD',
          'GES-PHD',
          'GES-PMN',
          'GLBLST-MIN',
          'GLBLST-VSI',
          'GPIH-PMN',
          'GR-AUD',
          'GR-CWRIT',
          'GR-NDO',
          'GR-NM',
          'GR-PD',
          'GR-SV',
          'GR-VR',
          'GS-BS',
          'GS-BSH',
          'GS-GRVR',
          'GS-MIN',
          'GS-MS',
          'GS-PD',
          'GS-PHD',
          'GS-PMN',
          'GS-VSI',
          'GSB-GRVR',
          'GSB-MA',
          'GSB-MBA',
          'GSB-MSM',
          'GSB-NM',
          'GSB-PD',
          'GSB-PHD',
          'GSB-PMN',
          'GSB-RF',
          'GSB-SNF',
          'GSB-VSI',
          'GYOB-GRVR',
          'GYOB-MF',
          'GYOB-PD',
          'HMN GEN-MS',
          'HRP',
          'HRP-GRVR',
          'HRP-MS',
          'HRP-PD',
          'HRP-PHD',
          'HSR-MF',
          'HSR-MS',
          'HSR-NM',
          'HSR-PD',
          'HSR-VR',
          'HSTEU-GRVR',
          'HSTRY-BA',
          'HSTRY-BAH',
          'HSTRY-BAS',
          'HSTRY-BASH',
          'HSTRY-GRVR',
          'HSTRY-MA',
          'HSTRY-MIN',
          'HSTRY-NM',
          'HSTRY-PD',
          'HSTRY-PHD',
          'HSTRY-PMN',
          'HSTRY-SEC',
          'HSTRYH-PHD',
          'HUMAN-BA',
          'HUMAN-BAH',
          'HUMAN-BAS',
          'HUMAN-BASH',
          'HUMAN-GRVR',
          'HUMAN-IHN',
          'HUMAN-MA',
          'HUMAN-MIN',
          'HUMBI-BA',
          'HUMBI-BAH',
          'HUMBI-BAS',
          'HUMBI-BASH',
          'HUMBI-BS',
          'HUMBI-BSH',
          'HUMBI-MIN',
          'HUMBI-SEC',
          'HUMBIO-NM',
          'HUMRTS-MIN',
          'HUMSC-VSI',
          'IDMEN-BAS',
          'IDMEN-BS',
          'IDMEN-BSH',
          'IDMHS-BA',
          'IDMHS-BAH',
          'IDMHS-BAS',
          'IDMHS-BS',
          'IDMHS-BSH',
          'IDMJR-BA',
          'IDMJR-BAH',
          'IDMJR-BAS',
          'IDMJR-BS',
          'IDMJR-BSH',
          'IDSH-BA',
          'IDSH-BAH',
          'IE-BAS',
          'IE-BS',
          'IE-BSH',
          'IE-MIN',
          'IE-MS',
          'IE-PHD',
          'ILAC-BA',
          'ILAC-BAH',
          'ILAC-BAS',
          'ILAC-BASH',
          'ILAC-MA',
          'ILAC-NM',
          'ILAC-PHD',
          'ILAC-SEC',
          'ILACH-PHD',
          'IMMUN-GRVR',
          'IMMUN-MS',
          'IMMUN-NM',
          'IMMUN-PD',
          'IMMUN-PHD',
          'INSST-IHN',
          'INTLR-BA',
          'INTLR-BAH',
          'INTLR-BAS',
          'INTLR-BASH',
          'INTLR-MIN',
          'INTLR-SEC',
          'IPER-MS',
          'IPER-PHD',
          'IPS-MA',
          'IPS-NM',
          'ITAL-BA',
          'ITAL-BAH',
          'ITAL-BAS',
          'ITAL-MA',
          'ITAL-MIN',
          'ITAL-NM',
          'ITAL-PHD',
          'ITAL-PMN',
          'ITALF-BA',
          'ITALF-BAS',
          'ITI',
          'ITI-PD',
          'JAPAN-BA',
          'JAPAN-BAH',
          'JAPAN-BAS',
          'JAPAN-MA',
          'JAPAN-MIN',
          'JAPAN-PHD',
          'JAPAN-PMN',
          'JEWSH-IHN',
          'JEWSH-MIN',
          'LAMER-BA',
          'LAMER-BAH',
          'LAMER-BAS',
          'LAMER-GRVR',
          'LAMER-IHN',
          'LAMER-MA',
          'LAMER-MIN',
          'LAW-GRVR',
          'LAW-JD',
          'LAW-JSD',
          'LAW-JSM',
          'LAW-LLM',
          'LAW-MLS',
          'LAW-NM',
          'LAW-PD',
          'LING-BA',
          'LING-BAH',
          'LING-BAS',
          'LING-BASH',
          'LING-GRVR',
          'LING-MA',
          'LING-MIN',
          'LING-NM',
          'LING-PD',
          'LING-PHD',
          'LING-PMN',
          'LING-SEC',
          'LIT-MIN',
          'MATCS-BAS',
          'MATCS-BASH',
          'MATCS-BS',
          'MATCS-BSH',
          'MATCS-MIN',
          'MATCS-SEC',
          'MATH-BAS',
          'MATH-BASH',
          'MATH-BS',
          'MATH-BSH',
          'MATH-GRVR',
          'MATH-MIN',
          'MATH-MS',
          'MATH-NM',
          'MATH-PD',
          'MATH-PHD',
          'MATH-PMN',
          'MATH-SEC',
          'MATH-SNF',
          'MATH-VSI',
          'MATSC-BAS',
          'MATSC-BS',
          'MATSC-BSH',
          'MATSC-ENG',
          'MATSC-GRVR',
          'MATSC-MIN',
          'MATSC-MS',
          'MATSC-NM',
          'MATSC-PD',
          'MATSC-PHD',
          'MATSC-PMN',
          'MATSC-SEC',
          'MATSC-VSI',
          'MCP-MS',
          'MCP-PD',
          'MCP-PHD',
          'MCP-VSI',
          'MDIEV-MIN',
          'ME-BAS',
          'ME-BS',
          'ME-BSH',
          'ME-ENG',
          'ME-GRVR',
          'ME-MIN',
          'ME-MS',
          'ME-NM',
          'ME-PD',
          'ME-PHD',
          'ME-PMN',
          'ME-SNF',
          'ME-VSI',
          'MED-EXCH',
          'MED-GRVR',
          'MED-MD',
          'MED-MF',
          'MED-MS',
          'MED-NM',
          'MED-PD',
          'MEDIS-GRVR',
          'MEDIS-MF',
          'MEDIS-MS',
          'MEDIS-NM',
          'MEDIS-PD',
          'MEDIS-PHD',
          'MEDST-MIN',
          'MELLC-MIN',
          'MGMTS-GRVR',
          'MGTSC-BAS',
          'MGTSC-BS',
          'MGTSC-BSH',
          'MGTSC-GRVR',
          'MGTSC-MIN',
          'MGTSC-MS',
          'MGTSC-NM',
          'MGTSC-PD',
          'MGTSC-PHD',
          'MGTSC-PMN',
          'MGTSC-SEC',
          'MGTSC-UGVR',
          'MGTSC-VSI',
          'MGTSC2-PMN',
          'MI-GRVR',
          'MI-MF',
          'MI-MS',
          'MI-PD',
          'MI-PHD',
          'MLA-MLA',
          'MLASC-GRVR',
          'MLASC-MS',
          'MODLAN-MIN',
          'MOLCL-GRVR',
          'MOLPH-GRVR',
          'MPHA-MS',
          'MPHA-PD',
          'MPHA-PHD',
          'MTLIT-MA',
          'MTLIT-PD',
          'MTLIT-PHD',
          'MTLITH-PHD',
          'MUSIC-BA',
          'MUSIC-BAH',
          'MUSIC-BAS',
          'MUSIC-BASH',
          'MUSIC-DMA',
          'MUSIC-GRVR',
          'MUSIC-MA',
          'MUSIC-MIN',
          'MUSIC-NM',
          'MUSIC-PD',
          'MUSIC-PHD',
          'MUSIC-VSI',
          'MUSICH-PHD',
          'MUSOT-GRVR',
          'NATAM-BA',
          'NATAM-BAH',
          'NATAM-MIN',
          'NATAM-SEC',
          'NBIO-GRVR',
          'NBIO-PD',
          'NEUR-GRVR',
          'NEUR-MF',
          'NEUR-PD',
          'NEURS-GRVR',
          'NEURS-MS',
          'NEURS-PD',
          'NEURS-PHD',
          'NEURS-SNF',
          'NIS-PD',
          'NSUR-GRVR',
          'NSUR-MF',
          'NSUR-PD',
          'NSUR-VSI',
          'OHNS-GRVR',
          'OHNS-MF',
          'OHNS-PD',
          'ONC-GRVS',
          'OPHT-GRVR',
          'OPHT-MF',
          'OPHT-PD',
          'OR-MS',
          'OR-PHD',
          'ORTH-MF',
          'ORTH-PD',
          'ORTHO-GRVR',
          'PAS-MS',
          'PATH-GRVR',
          'PATH-MF',
          'PATH-PD',
          'PATH-VSI',
          'PEDS-GRVR',
          'PEDS-MF',
          'PEDS-PD',
          'PEDS-VSI',
          'PETEN-BS',
          'PETEN-ENG',
          'PETEN-GRVR',
          'PETEN-MS',
          'PETEN-NM',
          'PETEN-PD',
          'PETEN-PHD',
          'PETEN-SEC',
          'PHILO-BA',
          'PHILO-BAH',
          'PHILO-BAS',
          'PHILO-BASH',
          'PHILO-GRVR',
          'PHILO-MA',
          'PHILO-MIN',
          'PHILO-NM',
          'PHILO-PD',
          'PHILO-PHD',
          'PHILO-PMN',
          'PHILO-SEC',
          'PHILOH-PHD',
          'PHOSCI-PD',
          'PHREL-BA',
          'PHREL-BAH',
          'PHREL-BAS',
          'PHREL-BASH',
          'PHYS-BAS',
          'PHYS-BASH',
          'PHYS-BS',
          'PHYS-BSH',
          'PHYS-GRVR',
          'PHYS-MIN',
          'PHYS-MS',
          'PHYS-NM',
          'PHYS-PD',
          'PHYS-PHD',
          'PHYS-PMN',
          'PHYS-SEC',
          'PHYS-VSI',
          'PLA-PMN',
          'POLSC-BA',
          'POLSC-BAH',
          'POLSC-BAS',
          'POLSC-BASH',
          'POLSC-GRVR',
          'POLSC-MA',
          'POLSC-MIN',
          'POLSC-NM',
          'POLSC-PD',
          'POLSC-PHD',
          'POLSC-PMN',
          'POLSC-SEC',
          'POLSC-SNF',
          'POLSC-VSI',
          'PORT-MIN',
          'PPA-PD',
          'PSY-PMN',
          'PSYC-GRVR',
          'PSYC-MF',
          'PSYC-PD',
          'PSYC-VSI',
          'PSYCH-BA',
          'PSYCH-BAH',
          'PSYCH-BAS',
          'PSYCH-BASH',
          'PSYCH-GRVR',
          'PSYCH-IHN',          
          'PSYCH-MA',
          'PSYCH-MIN',
          'PSYCH-NM',
          'PSYCH-PD',
          'PSYCH-PHD',
          'PSYCH-PMN',
          'PSYCH-SEC',
          'PSYCH-SNF',
          'PSYCH-VSI',
          'PSYOT-GRVR',
          'PUBPO-BA',
          'PUBPO-BAH',
          'PUBPO-BAS',
          'PUBPO-MA',
          'PUBPO-MIN',
          'PUBPO-MPP',
          'PUBPO-NM',
          'PUBPO-SEC',
          'RAD-GRVR',
          'RAD-MF',
          'RAD-PD',
          'RAD-VSI',
          'RADO-GRVR',
          'RADO-MF',
          'RADO-PD',
          'RADO-VSI',
          'REES-GRVR',
          'REES-MA',
          'REES-MIN',
          'REES-PD',
          'RELST-BA',
          'RELST-BAH',
          'RELST-BAS',
          'RELST-BASH',
          'RELST-GRVR',
          'RELST-IHN',
          'RELST-MA',
          'RELST-MIN',
          'RELST-NM',
          'RELST-PD',
          'RELST-PHD',
          'RELST-PMN',
          'RELSTH-PHD',
          'RUSS-MA',
          'SBIO-NM',
          'SBIO-PD',
          'SBIO-PHD',
          'SBIO-VSI',
          'SCBRM-GRVR',
          'SCBRM-MF',
          'SCBRM-PD',
          'SCBRM-PHD',
          'SCCM-MS',
          'SCCM-PHD',
          'SCCM-PMN',
          'SLAV-BA',
          'SLAV-BAH',
          'SLAV-BAS',
          'SLAV-BASH',
          'SLAV-GRVR',
          'SLAV-MA',
          'SLAV-MIN',
          'SLAV-NM',
          'SLAV-PHD',
          'SLAV-PMN',
          'SOCIO-BA',
          'SOCIO-BAH',
          'SOCIO-BAS',
          'SOCIO-BASH',
          'SOCIO-GRVR',
          'SOCIO-MA',
          'SOCIO-MIN',
          'SOCIO-NM',
          'SOCIO-PD',
          'SOCIO-PHD',
          'SOCIO-PMN',
          'SOCIO-SEC',
          'SOCIO-VSI',
          'SPAN-BA',
          'SPAN-BAH',
          'SPAN-BAS',
          'SPAN-BASH',
          'SPAN-MA',
          'SPAN-MIN',
          'SPAN-PHD',
          'SPAN-SEC',
          'SPANH-PHD',
          'STATS-GRVR',
          'STATS-MIN',
          'STATS-MS',
          'STATS-NM',
          'STATS-PD',
          'STATS-PHD',
          'STATS-PMN',
          'STATS-VSI',
          'STMRM-PHD',
          'STMRM-VSI',
          'STRBIOGRVR',
          'STS-BA',
          'STS-BAH',
          'STS-BAS',
          'STS-BASH',
          'STS-BS',
          'STS-BSH',
          'STS-IHN',
          'STS-MIN',
          'STS-PD',
          'STS-SEC',
          'SURG-GRVR',
          'SURG-MF',
          'SURG-PD',
          'SURG-VSI',
          'SUSTSCI-MA',
          'SUSTSCI-MS',
          'SYMBO-BAS',
          'SYMBO-BASH',
          'SYMBO-BS',
          'SYMBO-BSH',
          'SYMBO-MIN',
          'SYMBO-MS',
          'SYMBO-SEC',
          'THPST-BA',
          'THPST-BAH',
          'THPST-BAS',
          'THPST-BASH',
          'THPST-MA',
          'THPST-MIN',
          'THPST-NM',
          'THPST-PD',
          'THPST-PHD',
          'TRANS-MIN',
          'UGNM-GNM',
          'UGNM-HSA',
          'UGNM-HSI',
          'UGNM-HSV',
          'UGNM-NHSA',
          'UGNM-SV',
          'UGNM-SVR',
          'UGNM-VR',
          'URBST-BA',
          'URBST-BAH',
          'URBST-BAS',
          'URBST-BASH',
          'URBST-MIN',
          'URBST-SEC',
          'UROL-GRVR',
          'UROL-MF',
          'UROL-PD',
          'VTSS-BA'
          ]
